apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker
spec:
  ports:
    - name: worker
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: worker
